### ISSUE TITLE
Image size too big

### ISSUE THREAD

**Issue by ozym4nd145** [devclub-iitd/DevClubWebsite#5]
Website is too slow to load due to large image sizes. Shrink the image size to < 500KB for all images (most  of them are already below it).

**Comment by Siddhant24** [comment]
The images with sizes greater than 500 KB are arsh.jpg, background.jpg, falshsubs.png ( 2,7 MB ), sendata.jpg, studyportal.jpg.

**Comment by Siddhant24** [comment]
Images optimised. Largest image now has size 60 KB. All images put together have size 420 KB.
